site_name: Dataista
site_description: Dataista
site_url: https://adriana-hemann.github.io/Dataista-website/
watch: ["docs", "mkdocs.yml"]

nav:
    - Home: index.html
    - About: about.md
    - Services: services.md
    - Contact: contactus.md

copyright: Copyright &copy; 2024 Dataista

extra_css:
  - stylesheets/extra.css

extra:
    social:
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/AristaNetworks
    - icon: fontawesome/solid/globe
      link: https://dataista.io

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml

    features:
        - content.code.annotate
        - content.code.copy
        - content.tabs.link
        - content.tooltips
        - header.autohide
        - navigation.top
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
        # - toc.follow
        # - toc.integrate

    favicon: assets/logo.png

    font:
        text: Roboto
        code: Fira Mono

    language: en

    logo: assets/logo.png

    palette:
        - media: "(prefers-color-scheme: dark)"
          scheme: default
          primary: custom

markdown_extensions:
    - abbr
    - admonition
    - attr_list
    - def_list
    - footnotes
    - md_in_html
    - pymdownx.arithmatex
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.tilde
    - tables
    # - toc:
    #     permalink: true
    #     toc_depth: 1
    

plugins:
    - git-revision-date
    - glightbox
    - search:
        lang: en